genotype_api/models.py, tests/test_genotype_api.py
- plates/{id} endpoint returning PlateReadWithAnalyses
- PlateReadWithAnalyses contains AnalysisReadWithSample
=> read palte with analysis with sample

genotype_api/api/endpoints/plates.py
- setting signed_by
- method and version are ints
=> setting signed user

genotype_api/api/endpoints/plates.py, genotype_api/models.py
plates endpoint returning plate with user
=> plate with user

genotype_api/api/endpoints/plates.py, genotype_api/crud/analyses.py
- status code and repsonce details to post plate
=> Create plate responce

genotype_api/api/endpoints/samples.py, genotype_api/match.py
* Return appropriate status code when sample check fails predictably
=> Handle checking without both analyses

genotype_api/security.py
* Enable service account auth via jose
=> Enable service auth via jose

genotype_api/api/endpoints/samples.py, genotype_api/config.py, genotype_api/models.py, genotype_api/security.py, requirements.txt
=> Match functionality

genotype_api/api/endpoints/samples.py
* Get /samples/ result automatically sorted 
=> Automatically sort sample results

genotype_api/api/endpoints/samples.py
* Add date span to match query to speed up search
=> Add time span to match query

genotype_api/api/endpoints/samples.py
* Endpoint for manual set status
=> Manual set status endpoint

genotype_api/api/endpoints/plates.py, genotype_api/constants.py, genotype_api/crud/samples.py, genotype_api/models.py
* Plates list returns stats
* GET plate/plate_id returns stats
=> Plate stats

genotype_api/api/endpoints/plates.py, genotype_api/api/endpoints/samples.py, genotype_api/match.py, genotype_api/models.py
=> add sample status

genotype_api/api/endpoints/plates.py, genotype_api/api/endpoints/samples.py, genotype_api/match.py, genotype_api/models.py
=> Add nested structure for sample detail

genotype_api/api/endpoints/samples.py
* Fix check for updating sample status automatically
=> Fix confition for auto update of sample status

genotype_api/api/endpoints/samples.py, requirements.txt
=> add equality

.github/workflows/black.yml, Dockerfile, setup.py
=> feat(python): Update

genotype_api/api/endpoints/plates.py, genotype_api/api/endpoints/samples.py, genotype_api/database/crud/delete.py, genotype_api/database/crud/read.py, genotype_api/database/models.py, genotype_api/file_parsing/excel.py, genotype_api/models.py, genotype_api/security.py
=> feat(pep_0604):

genotype_api/api/endpoints/analyses.py, genotype_api/database/crud/read.py
Move database statements out of analysis api
=> refactor(analysis endpoint session handling)

genotype_api/api/endpoints/plates.py, genotype_api/database/crud/read.py, genotype_api/database/filter_models/plate_models.py
Plate sign off bug - closes : #110
=> fix(plate sign off bug)

genotype_api/dto/plate.py
=> fix( validator)

genotype_api/dto/plate.py
added a fix to fetch proper status counts Closes: #116
=> fix(status counts)

genotype_api/api/endpoints/analyses.py, genotype_api/api/endpoints/plates.py, genotype_api/api/endpoints/users.py, genotype_api/database/crud/create.py, genotype_api/dto/analysis.py, genotype_api/dto/plate.py, genotype_api/dto/user.py, genotype_api/exceptions.py, genotype_api/services/analysis_service/analysis_service.py, genotype_api/services/plate_service/plate_service.py, genotype_api/services/user_service/user_service.py
User service to translate crud layer to api layer
=> add(user service)

genotype_api/api/endpoints/snps.py, genotype_api/dto/snp.py, genotype_api/exceptions.py, genotype_api/services/snp_service/snp_service.py
=> add(snp service)

genotype_api/services/endpoint_services/sample_service.py
=> bug(fix gentype mismatch error)

genotype_api/api/endpoints/plates.py, genotype_api/database/crud/read.py, genotype_api/exceptions.py, genotype_api/file_parsing/excel.py, genotype_api/services/endpoint_services/plate_service.py
=> fix(plate upload)

poetry.lock
=> feat(update): idna

poetry.lock
=> feat(update): fastapi

poetry.lock
=> feat(update): cryptography

poetry.lock
=> feat(update): python-multipart
